name: gtrends_bass_app
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - pandas=2.3.1
  - numpy=2.2.6
  - plotly=6.3.0
  - streamlit=1.48.1
  - scikit-learn=1.7.1
  - matplotlib=3.10.5
  - pymc=5.23.0
  - pymc-marketing=0.15.0
  - pip=25.2
  - pip:
      - pytrends==4.9.2